export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const USER_INPUT_CHANGED_LOGIN = 'USER_INPUT_CHANGED_LOGIN';
export const USER_INPUT_CHANGED_PASSWORD = 'USER_INPUT_CHANGED_PASSWORD';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOG_OUT = 'USER_LOG_OUT';