export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const USER_INPUT_CHANGED_LOGIN = 'USER_INPUT_CHANGED_LOGIN';
export const USER_INPUT_CHANGED_PASSWORD = 'USER_INPUT_CHANGED_PASSWORD';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOG_OUT = 'USER_LOG_OUT';

export const NEW_USER_INPUT_CHANGED_LOGIN = 'NEW_USER_INPUT_CHANGED_LOGIN';
export const NEW_USER_INPUT_CHANGED_PASSWORD = 'NEW_USER_INPUT_CHANGED_PASSWORD';
export const USER_REGISTRATION = 'USER_REGISTRATION';

export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILED = 'GET_ARTICLE_FAILED';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';

export const IS_LIKE = 'IS_LIKE';

export const NAVIGATION = 'NAVIGATION';
export const NAVIGATION_OPEN = 'NAVIGATION_OPEN';

export const USER_COMMENT_CHANGED = 'USER_COMMENT_CHANGED';
export const USER_COMMENT_SUBMIT = 'USER_COMMENT_SUBMIT';
