export const USER_INPUT_LOGIN_CHANGED_LOG = 'USER_INPUT_LOGIN_CHANGED_LOG';
export const USER_INPUT_LOGIN_CHANGED_PASS = 'USER_INPUT_LOGIN_CHANGED_PASS';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';

export const USER_INPUT_REGISTRATION_CHANGED_LOG = 'USER_INPUT_REGISTRATION_CHANGED_LOG';
export const USER_INPUT_REGISTRATION_CHANGED_PASS = 'USER_INPUT_REGISTRATION_CHANGED_PASS';
export const USER_REGISTRATION = 'USER_REGISTRATION';
